// <auto-generated />
using System;
using Hindsight.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hindsight.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Hindsight.Domain.Entities.AssetPriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAtYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AssetPriceSnapshots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e42faa1-0433-9de8-89fa-ddcf3d3686d2"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 279.10m,
                            Year = 2000
                        },
                        new
                        {
                            Id = new Guid("8eaca92e-002a-1321-246f-8ee09a8cde59"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 271.04m,
                            Year = 2001
                        },
                        new
                        {
                            Id = new Guid("2555b708-5a6b-b94b-f86f-90659fbc423f"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 309.73m,
                            Year = 2002
                        },
                        new
                        {
                            Id = new Guid("266ce76c-0679-843c-9367-cd394d270217"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 363.38m,
                            Year = 2003
                        },
                        new
                        {
                            Id = new Guid("e4684a08-f144-a068-139b-1bbd77e25cf3"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 409.72m,
                            Year = 2004
                        },
                        new
                        {
                            Id = new Guid("0a30117c-0298-9d49-1c17-c3864086e150"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 444.74m,
                            Year = 2005
                        },
                        new
                        {
                            Id = new Guid("e7cfaeb4-4160-4674-4d55-d281e10693a6"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 603.46m,
                            Year = 2006
                        },
                        new
                        {
                            Id = new Guid("d42a77c6-4f58-4fb3-b4b8-8375b72554a4"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 695.39m,
                            Year = 2007
                        },
                        new
                        {
                            Id = new Guid("a1e2e521-c838-8d79-06f6-33a6d0b79d8e"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 871.96m,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("9e9227d3-cbc7-cc9c-1abd-19019be8f309"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 972.35m,
                            Year = 2009
                        },
                        new
                        {
                            Id = new Guid("b368bea0-e46a-6257-8209-7558e9c903e4"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1224.52m,
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("6161a52c-149a-016d-6009-6f0311e376ca"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1571.52m,
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("0b229771-f64a-c152-34c1-d0ea13f4eb48"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1668.98m,
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("642b5991-ad88-d050-8e07-5fb2555fe6ea"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1411.23m,
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("ce764ee1-7255-0196-c634-7cc7557ae5f6"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1266.40m,
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("50f30032-fe8d-0477-1b18-a3844c093871"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1160.06m,
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("4e4db56f-499c-b84b-b6d1-bd5c2eedebe8"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1248.07m,
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("cc73c274-17e9-b49d-14c5-8af4a6a3f833"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1257.15m,
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("290bdb40-cff5-a6e9-b24b-a465604f222e"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1268.49m,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("eec5916d-d2c7-9bfb-3aa0-1e8322210042"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1392.60m,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("e19aaaaa-6a42-e91d-d13f-06e13bec62c2"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1769.64m,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("4477de1d-936d-f548-2e94-5ed9ce0afe96"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1798.61m,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("ff53a303-1598-f921-1902-2d00093f323c"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1800.09m,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("e172cabb-6bc2-a6b0-7680-305fa298c535"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 1940.54m,
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("8efad27f-023b-62f6-7889-637d9413c093"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 2350.00m,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("b2b6ee68-3e38-3758-fb5c-03c983166686"),
                            AssetName = "Gold",
                            AssetType = "Commodity",
                            PriceAtYear = 2650.00m,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("50785246-3180-551f-33e6-e5b133d54010"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 4.95m,
                            Year = 2000
                        },
                        new
                        {
                            Id = new Guid("1f2d16ec-407a-e3fb-e7f2-8653030f04fa"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 4.37m,
                            Year = 2001
                        },
                        new
                        {
                            Id = new Guid("81d78ad6-d42f-91cd-a300-f5c71c267c75"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 4.60m,
                            Year = 2002
                        },
                        new
                        {
                            Id = new Guid("00d072c5-e8d7-be3c-9fef-3b87900ca726"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 4.88m,
                            Year = 2003
                        },
                        new
                        {
                            Id = new Guid("cf0678a4-8a6f-e394-7624-6730b9012d24"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 6.67m,
                            Year = 2004
                        },
                        new
                        {
                            Id = new Guid("faef70b1-5739-a2b7-bd66-50c2ed19993a"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 7.32m,
                            Year = 2005
                        },
                        new
                        {
                            Id = new Guid("a0f6df0f-b0cc-1ac7-496f-5057ea2b52cc"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 11.55m,
                            Year = 2006
                        },
                        new
                        {
                            Id = new Guid("55e2e399-9bd5-3a27-9cd7-d0ded54ac4c5"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 13.38m,
                            Year = 2007
                        },
                        new
                        {
                            Id = new Guid("a19cdd30-c76b-b346-77a9-efc45a83671d"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 14.99m,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("d79cc4e1-a031-f080-3b35-9b0d7cd37e55"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 14.67m,
                            Year = 2009
                        },
                        new
                        {
                            Id = new Guid("fe87f20b-03fa-fb3f-796f-800eb45717e5"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 20.19m,
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("7b0a8148-c504-87f5-449d-005cc17f410b"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 35.12m,
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("c29c2535-a6a4-3331-1ba6-48510c5ccb2d"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 31.15m,
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("e2c6ed24-f161-7123-c990-634d227d1af5"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 23.79m,
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("07f3680c-1910-c7ed-3553-f718260c0cd9"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 19.08m,
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("c502de75-fa05-d444-a49c-3551b3d0a445"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 15.68m,
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("c4f538df-6fbb-00de-ffbf-20a656fceb5e"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 17.14m,
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("493346d5-19df-bb5c-3094-9f8de7e379e3"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 17.04m,
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("9199fc68-07da-177b-75d3-53c3ee702893"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 15.71m,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("f6daa409-0ea0-444b-eee9-53bac641b869"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 16.21m,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("a581e4ee-d97e-6685-b0fa-704621534ce1"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 20.55m,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("ee74dbf4-8ae8-2122-2887-2fdbd616ebac"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 25.14m,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("6b9cdf43-82a1-f896-aecb-9fca76185643"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 21.76m,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("a6a3caee-1275-ebdf-ee28-18379c668ce7"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 23.35m,
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("860ec988-095b-328a-a5ff-b312c69787ef"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 28.50m,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("1b4ee125-e573-afda-2efd-03350d85aaf7"),
                            AssetName = "Silver",
                            AssetType = "Commodity",
                            PriceAtYear = 32.20m,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("a8a23041-22e0-1a6b-0e43-2fbc2408eae4"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 1.00m,
                            Year = 2000
                        },
                        new
                        {
                            Id = new Guid("d9a67152-49f3-9885-d32c-45d966a61f5b"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 0.39m,
                            Year = 2001
                        },
                        new
                        {
                            Id = new Guid("c6b9c556-2cb5-ed46-f04e-724e05313801"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 0.26m,
                            Year = 2002
                        },
                        new
                        {
                            Id = new Guid("51c55874-73d5-b4b6-26df-95d527dd2a21"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 0.33m,
                            Year = 2003
                        },
                        new
                        {
                            Id = new Guid("621c05d2-e54f-ccd9-57de-3365c6da338f"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 0.61m,
                            Year = 2004
                        },
                        new
                        {
                            Id = new Guid("0a7fd477-3165-c423-3319-f2809d66cc5d"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 1.67m,
                            Year = 2005
                        },
                        new
                        {
                            Id = new Guid("2653d078-931a-4173-20bc-92cccf37b2e8"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 2.52m,
                            Year = 2006
                        },
                        new
                        {
                            Id = new Guid("0fff1b80-585a-e4f3-0f39-6f8d003b5aff"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 4.58m,
                            Year = 2007
                        },
                        new
                        {
                            Id = new Guid("5186612f-ddc6-8b98-50ad-92269eab81ed"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 5.07m,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("b5f4986a-e5b1-0594-ebc9-0ebc7d0f7a0b"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 5.23m,
                            Year = 2009
                        },
                        new
                        {
                            Id = new Guid("65a51355-37ee-146a-1f67-5c562eaaab6d"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 9.28m,
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("248e1472-5c6e-2177-70ba-af863245021d"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 13.00m,
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("5e00f243-3a59-5b0c-7e15-fdb9ec850ab8"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 20.64m,
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("41c22e7f-211e-ddad-0506-0d266d038856"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 16.88m,
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("b2ac5c45-5bc1-295e-a3cc-d78565cb7c2c"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 23.05m,
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("bc2fda87-3501-3cab-8e14-a6eb2dfb4a02"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 27.31m,
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("7fcfcbb9-826e-f62f-4c81-e4633baa429b"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 26.15m,
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("92361cdc-4672-9cbc-aad1-a833c309bc13"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 37.64m,
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("78ec88a3-b4fc-f5dc-f88c-91412628e8c0"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 47.27m,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("3b743308-8611-3876-5107-24a4f99a65f5"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 52.09m,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("bdba3c42-1106-dd8b-ab3b-32a0a2edc5bb"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 95.34m,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("e355976b-65ef-6edb-803e-3f9ab3522a93"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 140.98m,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("67d49196-62b7-0a96-476c-7f8b2865eab7"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 154.51m,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("efc02c6e-79b8-d38d-d1f6-0ea36a86b365"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 172.62m,
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("51704b1e-507f-799a-2fe3-c82d1a4dab35"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 180.00m,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("d2fd1577-7f20-5efd-ec49-4aae0c90a7a3"),
                            AssetName = "Apple",
                            AssetType = "Stock",
                            PriceAtYear = 220.00m,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("2b8565b5-8768-6bdd-5f09-23431e18106f"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 0.50m,
                            Year = 2002
                        },
                        new
                        {
                            Id = new Guid("74012ca9-d060-3298-3e7e-4333d9255247"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 1.20m,
                            Year = 2003
                        },
                        new
                        {
                            Id = new Guid("ffaa90c5-4038-1a33-f093-6c27ea835643"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 1.80m,
                            Year = 2004
                        },
                        new
                        {
                            Id = new Guid("f209fe49-811b-ec2d-8020-a8bf815f94ab"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 1.95m,
                            Year = 2005
                        },
                        new
                        {
                            Id = new Guid("212c421f-4942-330d-21c7-4ca3c919446c"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 3.40m,
                            Year = 2006
                        },
                        new
                        {
                            Id = new Guid("3ab77047-8ae1-b48b-4116-1a8bd3a8b626"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 3.10m,
                            Year = 2007
                        },
                        new
                        {
                            Id = new Guid("3aa1f044-0d09-9046-c608-568211e5b9ba"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 4.10m,
                            Year = 2008
                        },
                        new
                        {
                            Id = new Guid("8bee5c71-d83f-ecf0-2494-6869856cf82c"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 6.30m,
                            Year = 2009
                        },
                        new
                        {
                            Id = new Guid("4509aa5c-2d4c-69a1-805f-57e3155e0b5b"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 16.80m,
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("d58cbc07-9efe-d76a-d1d3-d95c695a1241"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 27.20m,
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("52052cac-9b9f-c117-1ea1-84b908a87eb1"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 11.90m,
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("b711ae1c-10de-32ae-6798-ebd7813f636f"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 35.30m,
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("609ff569-61d3-401f-6a04-0ad7a7d76872"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 63.10m,
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("ef295e5c-b23c-6458-39e7-8facd8c35938"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 91.80m,
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("507960b1-cc55-946f-7a78-39ac8ee1da1d"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 102.10m,
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("cddf03b1-4da9-7746-6a99-02234bc1e7cc"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 165.40m,
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("80c66de0-b5dc-35e3-3797-a400d1a88647"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 310.20m,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("d41ccb06-f425-8646-2a32-3f92c7499359"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 325.90m,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("1620d3c5-e003-da6a-ee7b-31344a9aeb2c"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 480.20m,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("672f86a4-35c2-28e8-f48d-9f39086c1b69"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 580.50m,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("55c43713-16ca-7208-a19a-73645fa758a2"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 290.10m,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("fbc5a668-e980-11e2-1acd-e663f5a13bab"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 410.80m,
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("97584059-547e-9c57-87f3-4343dc71283e"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 610.00m,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("0b226bb2-1913-f4f3-754c-4db07b8015ba"),
                            AssetName = "Netflix",
                            AssetType = "Stock",
                            PriceAtYear = 720.00m,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("85927da0-a498-917f-e1cc-80e641c6bc9e"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 0.10m,
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("88a08cac-7a08-7825-8b32-b4995fe799ea"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 5.50m,
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("ce4aa45e-e908-7afd-e586-54fabfb408ed"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 8.20m,
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("fabd2bd9-c8cb-006a-bb03-0b6ec76a45e5"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 189.54m,
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("1c179a44-09dd-4d7c-3a4a-b37cdc2d83b3"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 526.00m,
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("cece7303-9aac-f4b7-25e2-4202362653db"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 272.00m,
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("7569ec0b-bb56-8886-ea8c-cc2969d2de0d"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 567.00m,
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("5b06394d-32b5-e8ee-5298-912a8f465dd7"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 4000.00m,
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("cc6ba934-032f-c9dc-6f68-a39e07b50eb9"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 7558.00m,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("6c099dc9-8c89-e890-c7fa-0bafc4099f9e"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 7193.00m,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("b8746e24-ee12-65eb-a2fc-e02c3d687cf4"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 11116.00m,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("6bbe5209-c307-1643-f442-d6db4a94927e"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 47417.00m,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("54daf955-489e-2e09-d4ca-d7703be22e9a"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 28198.00m,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("16450fdb-b1d8-5a0a-a822-4af22fbaba57"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 28543.00m,
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("55f50372-fda7-6713-20a5-ca330181a182"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 65000.00m,
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("36a713aa-8b1d-1dd0-e1fb-8d945ebecd04"),
                            AssetName = "Bitcoin",
                            AssetType = "Crypto",
                            PriceAtYear = 95000.00m,
                            Year = 2025
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
